/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EPS;

import java.awt.FileDialog;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class EPSAdmin extends javax.swing.JFrame {

    private EPS administrar;
    private Pedido pedido;
    /**
     * Creates new form EPSAdmin
     * @param instance
     */
    public EPSAdmin(EPS instance) {
        initComponents();
        administrar = instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a la EPS");

        jLabel2.setText("Vacunas a pedir:");

        jLabel3.setText("Vac 1");

        jButton1.setText("Confirmar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("0");

        jLabel4.setText("Vac 2");

        jTextField2.setText("0");

        jLabel5.setText("Vac 3");

        jTextField3.setText("0");

        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Leer Archivo Usuarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FileDialog dialog = new FileDialog((Frame)null, "Select File to Open");
        dialog.setMode(FileDialog.LOAD);
        dialog.setVisible(true);
        String directory = dialog.getDirectory();
        String file = dialog.getFile();
        System.out.println(directory+file + " chosen.");
        if(administrar.leerUsuarios(directory+file))
        {
            pedido = new Pedido(administrar.getPersonasAmparadas());
            DefaultListModel dlm = new DefaultListModel();
            for(Usuario dale: administrar.getPersonasAmparadas())
            {
                if(!dale.isAtendido())
                    dlm.addElement(dale);
            }
            jList1.setModel(dlm);
            jTextField1.setText(Integer.toString(pedido.getCantVac1()));
            jTextField2.setText(Integer.toString(pedido.getCantVac2()));
            jTextField3.setText(Integer.toString(pedido.getCantVac3()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Hubo un error leyendo el archivo");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if((Integer.parseInt(jTextField1.getText())) + (Integer.parseInt(jTextField2.getText())) + (Integer.parseInt(jTextField3.getText())) >= 10)
        {
            String resultado = administrar.iniciarPedido(pedido);
            if(resultado != null)
            {
                String[] parts = new String[3];
                jList1.clearSelection();
                parts = resultado.split(",", 3);
                pedido.setCantVac1(Integer.parseInt(parts[0]));
                jTextField1.setText(parts[0]);
                pedido.setCantVac2(Integer.parseInt(parts[1]));
                jTextField2.setText(parts[1]);
                pedido.setCantVac3(Integer.parseInt(parts[2]));
                jTextField3.setText(parts[2]);
                DefaultListModel dlm = new DefaultListModel();
                if(pedido.getCantVac1() != 0)
                {
                    for(Usuario dale: administrar.getPersonasAmparadas())
                    {
                        if(!dale.isAtendido() && dale.getVacPreferencia().equals(Vacuna.Vac1))
                            dlm.addElement(dale);
                    }
                }
                else{
                    for(Usuario dale: administrar.getPersonasAmparadas())
                    {
                        if(dale.getVacPreferencia().equals(Vacuna.Vac1))
                            dale.setAtendido(true);
                    }
                }
                if(pedido.getCantVac2() != 0)
                {
                    for(Usuario dale: administrar.getPersonasAmparadas())
                    {
                        if(!dale.isAtendido() && dale.getVacPreferencia().equals(Vacuna.Vac2))
                            dlm.addElement(dale);
                    }
                }else{
                    for(Usuario dale: administrar.getPersonasAmparadas())
                    {
                        if(dale.getVacPreferencia().equals(Vacuna.Vac2))
                            dale.setAtendido(true);
                    }
                }
                if(pedido.getCantVac3() != 0)
                {
                    for(Usuario dale: administrar.getPersonasAmparadas())
                    {
                        if(!dale.isAtendido() && dale.getVacPreferencia().equals(Vacuna.Vac3))
                            dlm.addElement(dale);
                    }
                }else{
                    for(Usuario dale: administrar.getPersonasAmparadas())
                    {
                        if(dale.getVacPreferencia().equals(Vacuna.Vac3))
                            dale.setAtendido(true);
                    }
                }
                System.out.println(administrar.getPersonasAmparadas().toString());
                jList1.setModel(dlm);
                JOptionPane.showMessageDialog(null, "La transacción se ha consumado con los siguientes resultados. \nVacuna 1: "+parts[0]+" faltantes.\nVacuna 2: "+parts[1]+" faltantes.\nVacuna 3: "+parts[2]+" faltantes.\n");
            }else{
                JOptionPane.showMessageDialog(null, "La transacción se ha anulado por alguna razón, intentelo de nuevo");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe tener por lo menos 10 vacunas para poder iniciar un pedido.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EPSAdmin().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
